### ISSUE TITLE
怎么用

### ISSUE THREAD

**Issue by wzhens** [yzsme/CCDGUTNetAuth#1]

**Comment by yzslab** [comment]
请给文件添加可执行权限：
```
chmod +x ccdgut-auth
```

**Comment by wzhens** [comment]
-ash: ccdgut-auth: not found

**Comment by wzhens** [comment]
经过测试破解多人共享的非常稳。  自动认证这个不会用辛苦大佬给详细介绍。 
认证那个没有请求头也可以认证成功，直接发包给10.20.208.198也可以直接认证成功

**Comment by wzhens** [comment]
wget --post-data "DDDDD=学号&upass=密码&R1=0&R2=&R3=0&R6=0&para=00&0MKKey=123456&buttonClicked=&redirect_url=&err_flag=&username=&password=&user=&cmd=&Login=&v6ip=" http://10.20.208.198/a70.htm
建议用wget。openwrt 一般没有curl的

**Comment by yzslab** [comment]
谢谢你的建议。
