### ISSUE TITLE
最新的登录地址已经变更

### ISSUE THREAD

**Issue by Ivaneus** [yzsme/CCDGUTNetAuth#2]
校园网学号认证的最新登录地址是192.168.100.1 原来的10.20.208.198已经凉了

**Comment by Ivaneus** [comment]
if  curl -i http://www.sina.com | grep -o 'http://*.*.*.*' | grep -q 'http://www.sina.com.cn/' ;then  	
			echo "已经联网"	
            sleep 60
	    else
		    echo "尚未联网"
			LoginAdress=$(curl -i http://www.sina.com | grep -o 'http://*.*.*.*')
			LoginAdress=${LoginAdress%$'\r'}
			echo $LoginAdress
提供一段可以自动获取登录地址的代码

**Comment by yzslab** [comment]
你好，谢谢你的提醒以及建议。
